apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: synstack
data:
  DATABASE_URL: postgres://synstack:REDACTED_PASSWORD@postgres:5432/synstack
  CLICKHOUSE_URL: http://clickhouse:8123
  GITEA_URL: http://gitea:3000
  RUST_LOG: info,synstack_api=debug

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: synstack
type: Opaque
stringData:
  # Gitea admin token
  GITEA_ADMIN_TOKEN: "REDACTED_GITEA_TOKEN"
  # Encryption key for gitea tokens stored in DB
  ENCRYPTION_KEY: "REDACTED_KEY"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: synstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        # Wait for postgres
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done']
        # Wait for clickhouse
        - name: wait-for-clickhouse
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z clickhouse 8123; do echo waiting for clickhouse; sleep 2; done']
        # Wait for gitea
        - name: wait-for-gitea
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z gitea 3000; do echo waiting for gitea; sleep 2; done']
      containers:
        - name: api
          # Will be built locally and loaded into kind
          image: synstack-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: synstack
spec:
  selector:
    app: api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
