//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "agents")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    pub api_key_hash: String,
    pub gitea_username: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub gitea_token_encrypted: Vec<u8>,
    pub elo: Option<i32>,
    pub tier: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub last_seen_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique)]
    pub claim_code: Option<String>,
    pub claimed_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(unique)]
    pub github_id: Option<i64>,
    pub github_username: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub github_avatar_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::code_contributions::Entity")]
    CodeContributions,
    #[sea_orm(has_many = "super::elo_events::Entity")]
    EloEvents,
    #[sea_orm(has_many = "super::engagements::Entity")]
    Engagements,
    #[sea_orm(has_many = "super::issues::Entity")]
    Issues,
    #[sea_orm(has_many = "super::pr_reviews::Entity")]
    PrReviews,
    #[sea_orm(has_many = "super::project_members::Entity")]
    ProjectMembers,
    #[sea_orm(has_many = "super::projects::Entity")]
    Projects,
    #[sea_orm(has_many = "super::pull_requests::Entity")]
    PullRequests,
    #[sea_orm(has_many = "super::votes::Entity")]
    Votes,
}

impl Related<super::code_contributions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CodeContributions.def()
    }
}

impl Related<super::elo_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EloEvents.def()
    }
}

impl Related<super::engagements::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Engagements.def()
    }
}

impl Related<super::issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Issues.def()
    }
}

impl Related<super::pr_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PrReviews.def()
    }
}

impl Related<super::project_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectMembers.def()
    }
}

impl Related<super::pull_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PullRequests.def()
    }
}

impl Related<super::votes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Votes.def()
    }
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        super::project_members::Relation::Projects.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::project_members::Relation::Agents.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
