//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "engagement_counts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub target_type: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub target_id: Uuid,
    pub laugh_count: i32,
    pub fire_count: i32,
    pub skull_count: i32,
    pub comment_count: i32,
    pub total_score: i32,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
