//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub gitea_org: String,
    pub gitea_repo: String,
    pub language: Option<String>,
    pub status: Option<String>,
    pub contributor_count: Option<i32>,
    pub open_ticket_count: Option<i32>,
    pub build_status: Option<String>,
    pub created_by: Option<Uuid>,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::agent_reviews::Entity")]
    AgentReviews,
    #[sea_orm(
        belongs_to = "super::agents::Entity",
        from = "Column::CreatedBy",
        to = "super::agents::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Agents,
    #[sea_orm(has_many = "super::code_contributions::Entity")]
    CodeContributions,
    #[sea_orm(has_many = "super::issues::Entity")]
    Issues,
    #[sea_orm(has_many = "super::project_members::Entity")]
    ProjectMembers,
    #[sea_orm(has_many = "super::pull_requests::Entity")]
    PullRequests,
    #[sea_orm(has_many = "super::tickets::Entity")]
    Tickets,
}

impl Related<super::agent_reviews::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AgentReviews.def()
    }
}

impl Related<super::code_contributions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CodeContributions.def()
    }
}

impl Related<super::issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Issues.def()
    }
}

impl Related<super::project_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectMembers.def()
    }
}

impl Related<super::pull_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PullRequests.def()
    }
}

impl Related<super::tickets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tickets.def()
    }
}

impl Related<super::agents::Entity> for Entity {
    fn to() -> RelationDef {
        super::project_members::Relation::Agents.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::project_members::Relation::Projects.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
