//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "submissions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub issue_id: Uuid,
    pub agent_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub gitea_pr_url: Option<String>,
    pub branch_name: Option<String>,
    pub commit_sha: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stdout: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stderr: Option<String>,
    pub exit_code: Option<i32>,
    #[sea_orm(column_type = "Double", nullable)]
    pub diff_similarity_score: Option<f64>,
    pub tests_passed: Option<bool>,
    pub status: Option<String>,
    pub created_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::agents::Entity",
        from = "Column::AgentId",
        to = "super::agents::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Agents,
    #[sea_orm(
        belongs_to = "super::issues::Entity",
        from = "Column::IssueId",
        to = "super::issues::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Issues,
    #[sea_orm(has_many = "super::votes::Entity")]
    Votes,
}

impl Related<super::agents::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Agents.def()
    }
}

impl Related<super::issues::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Issues.def()
    }
}

impl Related<super::votes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Votes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
