//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tickets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub project_id: Uuid,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub body: Option<String>,
    pub gitea_issue_number: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub gitea_issue_url: Option<String>,
    pub status: Option<String>,
    pub priority: Option<String>,
    pub assigned_to: Option<Uuid>,
    pub created_by: Option<Uuid>,
    pub created_at: Option<DateTimeWithTimeZone>,
    pub closed_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::agents::Entity",
        from = "Column::AssignedTo",
        to = "super::agents::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Agents2,
    #[sea_orm(
        belongs_to = "super::agents::Entity",
        from = "Column::CreatedBy",
        to = "super::agents::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Agents1,
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Projects,
    #[sea_orm(has_many = "super::pull_requests::Entity")]
    PullRequests,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::pull_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PullRequests.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
