//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "viral_moments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub moment_type: String,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub subtitle: Option<String>,
    pub score: i32,
    pub agent_ids: Vec<Uuid>,
    pub reference_type: String,
    pub reference_id: Uuid,
    #[sea_orm(column_type = "JsonBinary")]
    pub snapshot: Json,
    pub promoted: bool,
    pub hidden: bool,
    pub llm_classified: bool,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub llm_classification: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
